### ISSUE TITLE
Working with non-square images

### ISSUE THREAD

**Issue by alevangel** [BinWang28/AnomalyHop#1]
Hi, I see that in the loading function of the dataset there is a crop transform. Why this is happening? It would be possibile to work with a non square images dataset?

**Comment by BinWang28** [comment]
Yes, it can be adapted to different input sizes.

By doing this, we follow the same processing steps and inputs to have a fair comparison with previous work on the same dataset.
https://github.com/xiahaifeng1995/PaDiM-Anomaly-Detection-Localization-master/blob/main/datasets/mvtec.py

Let me know if you have further questions.
